---
title: "Week_10_Tan"
author: "Wanting Tan"
date: "April 22, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# Load Required Packages
library(shiny)
#library(tidyverse)
library(tidycensus)
```

```{r}
#Get data from API
source("api-keys.R")
census_api_key(api.key.UScensus)

# Define UI for application
ui <- fluidPage(
  # Application title
  titlePanel("American Community Survey"),

  # Sidebar Layout
  sidebarLayout(

    # SelectInput for State and Type of data
    sidebarPanel(

      selectInput("State", "State",
                  choices = state.abb,
                  selected = "NJ"),
     radioButtons("Type", "Type",
                   choices = list("median_gross_rent",
                                  "median_household_income",
                                  "ratio"), 
                   selected = "ratio")
    ),

    
    # Show a plot
    mainPanel(plotOutput("Plot"))
  )
)

# Define server logic required to draw a plot
server <- function(input, output) {

  reduced_df <- reactive({
        get_acs(
        geography = "tract",
        variables = c(median_gross_rent = "B25064_001" , median_household_income = "B19013_001"),
        state = input$State,
        geometry = TRUE
      ) %>% .[, -5] %>% data.frame() %>% 

      spread(key = variable, value = estimate) %>% 
      mutate(ratio = median_gross_rent / median_household_income)
  })

  
  output$Plot <- renderPlot({

    reduced_df() %>% 
    ggplot(aes_string(fill = input$Type)) + geom_sf() + ggtitle(input$Type) + 
      scale_fill_gradientn(colours = rainbow(7))
  })

}



# Run the application 
shinyApp(ui = ui, server = server)
```

